name: Lint tree and check format

on:
  push:
    branches:
    paths:
      - 'main/**'
      - 'contrib/**'
      - 'user/**'
      - 'src/**'

  pull_request:
    branches:
      - master
    paths:
      - 'main/**'
      - 'contrib/**'
      - 'user/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint tree and check format
    runs-on: ubuntu-latest
    steps:
      - name: Refresh packages
        run: sudo apt-get update && sudo apt-get install python3-pip

      - name: Install dependencies
        run: sudo pip3 install black flake8

      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Lint tree and check format
        run: sh .ci/lint.sh
